spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: homework
      username: sa
      password: sa
      authentication-database: admin