services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - '9090:9090'
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - network-homework
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    networks:
      - network-homework
volumes:
  grafana-storage: {}